version: 1.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
build:
  project: build/AlienIsolation.SkipSaveConfirmationDialog.sln
  verbosity: minimal
before_package:
- ps: >-
    $releases = "https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases"

    $name = "Ultimate-ASI-Loader.zip"

    $latestRelease = Invoke-WebRequest $releases/latest -Headers @{"Accept"="application/json"}

    $json = $latestRelease.Content | ConvertFrom-Json

    $latestVersion = $json.tag_name

    $url = "$releases/download/$latestVersion/$name"


    Start-FileDownload $url -FileName 'C:\Ultimate-ASI-Loader.zip'

    7z e c:\Ultimate-ASI-Loader.zip -oc:\Projects\$env:APPVEYOR_PROJECT_SLUG\bin\

    ren c:\Projects\$env:APPVEYOR_PROJECT_SLUG\bin\dinput8.dll winmm.dll
after_build:
- cmd: release.bat
artifacts:
- path: bin\AlienIsolation.SkipSaveConfirmationDialog.zip
deploy:
- provider: GitHub
  release: AlienIsolation.SkipSaveConfirmationDialog v$(appveyor_build_version)
  auth_token:
    secure: SXMI7bm5RKh5j1S8A8dnUP2HFw97xHHlJH+mA0hx819vtxOPCpMFY3aFZ+2v16ri